### ISSUE TITLE
i have a couple webms for adding

### ISSUE THREAD

**Issue by clipmaster2000** [PanIntegralus/discord.webm-compilation#12]
https://cdn.discordapp.com/attachments/163382741491122176/1156602474824745010/tame_impala.webm (broken)
https://cdn.discordapp.com/attachments/1150542434657386666/1155963862676414504/video_1_keyframes.webm
https://cdn.discordapp.com/attachments/1133818118066688123/1149719820850434079/the_greatest_of_them_all.webm
https://cdn.discordapp.com/attachments/1117538658740879451/1156605977160859758/cute_koishi.webm

**Comment by PanIntegrah** [comment]
Adding these to the list, thank you! Sorry for the late reply, next time open a pull request so I can push this faster :D
