### ISSUE TITLE
They're not completely patched.

### ISSUE THREAD

**Issue by clipmaster2000** [PanIntegralus/discord.webm-compilation#16]
Link embeds still work.

**Comment by PatoFlamejanteTV** [comment]
yes

**Comment by PatoFlamejanteTV** [comment]
i have an working link: https://cdn.discordapp.com/attachments/1173277912607236140/1192138073908199574/yolooo_sporadic.webm?ex=65a7fc19&is=65958719&hm=5a97fe9aa872fba4453c140a78e1e38b365b35e32299f02e486771359436cfcd&

**Comment by PatoFlamejanteTV** [comment]
https://cdn.discordapp.com/attachments/1173277912607236140/1192138073908199574/yolooo_sporadic.webm with out expiration date

**Comment by PanIntegrah** [comment]
Updated README.md, closing this issue now.
