### ISSUE TITLE
idea: make an github page

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [PanIntegralus/discord.webm-compilation#19]
I think it would be nice to make a page for this repository, especially because you just need to configure few what it automatically generates a page.

**Comment by PanIntegralus** [comment]
For a while there was a website, but it was hosted on a third-party website, not on GitHub Pages. Also, this is not a really serious project, so creating a whole website just to preview some webms seems really stupid and time consuming. Again, I don't have time to do that with this repo, but if you have free time to waste, create a PR for it!

**Comment by PatoFlamejanteTV** [comment]
Hi! I can't make a GitHub page with pull requests, you need to go into the `setting > pages > GitHub pages` and set the root to "/" or main

**Comment by PanIntegralus** [comment]
Oh yeah, but it needs to point to an HTML file or something, right?

**Comment by PatoFlamejanteTV** [comment]
> Oh yeah, but it needs to point to an HTML file or something, right?

Actually, **no**, you can use Jekyll (https://jekyllrb.com/) to automatic build an HTML version of the README.md.

*Check this for more info*
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll
