### ISSUE TITLE
Mostly of the link are broken/expired.

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [PanIntegralus/discord.webm-compilation#22]
Almost (if not all) of the links just returns "`This content is no longer available.`"

**We could make an "archive" and upload any glitched downloaded .webms to this repo**, that's because GitHub don't have the "Expiring links" problem.

**Comment by PatoFlamejanteTV** [comment]
I found a Wayback Machine link of this repository (from 2022), and all the webms works because the way Wayback Machine works, **but it's too slow to download all the webms** and may not work on Discord.

https://web.archive.org/web/20220804194450/https://github.com/PanIntegralus/discord.webm-compilation

**Comment by PanIntegralus** [comment]
> We could make an "archive" and upload any glitched downloaded .webms to this repo, that's because GitHub don't have the "Expiring links" problem.

I ain't gonna do this, but if you want to create a PR with this, I'll push it.

**Comment by PatoFlamejanteTV** [comment]
> > We could make an "archive" and upload any glitched downloaded .webms to this repo, that's because GitHub don't have the "Expiring links" problem.
> 
> I ain't gonna do this, but if you want to create a PR with this, I'll push it.

Ok, I'm making an PR that created a folder, and inside the folder, there's WEBMs, so people can send the link for Discord, or just download.
